routes/web.php
<?php

use App\Livewire\HomePage;
use App\Livewire\ContactPage;
use App\Livewire\TrainingsPage;
use App\Livewire\ApplicationsPage;
use Illuminate\Support\Facades\Route;
use App\Livewire\Admin\AdminLoginPage;
use App\Livewire\Admin\AdminDashboardPage;
use App\Livewire\Admin\AdminTrainingsPage;
use App\Http\Controllers\SessionController;
use App\Livewire\Admin\AdminApplicationsPage;
use App\Livewire\Admin\AdminTechnologiesPage;
use App\Livewire\Admin\AdminTrainingFormPage;
use App\Livewire\Admin\AdminTechnologyFormPage;
use App\Livewire\Admin\AdminApplicationFormPage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', HomePage::class)->name('home');

Route::get('applications', ApplicationsPage::class)->name('applications.index');

Route::get('trainings', TrainingsPage::class)->name('trainings.index');

Route::prefix('admin')->name('admin.')->group(function () {
	Route::get('login', AdminLoginPage::class)->name('login');
	Route::get('session/create', [SessionController::class, 'create'])->name('session.create');

	Route::middleware('auth')->group(function () {
		Route::get('dashboard', AdminDashboardPage::class)->name('dashboard');
		Route::get('session/destroy', [SessionController::class, 'destroy'])->name('session.destroy');

		Route::get('applications', AdminApplicationsPage::class)->name('applications');
		Route::get('applications/create', AdminApplicationFormPage::class)->name('applications.create');
		Route::get('applications/{application}/edit', AdminApplicationFormPage::class)->name('applications.edit');

		Route::get('technologies', AdminTechnologiesPage::class)->name('technologies');
		Route::get('technologies/create', AdminTechnologyFormPage::class)->name('technologies.create');
		Route::get('technologies/{technology}/edit', AdminTechnologyFormPage::class)->name('technologies.edit');

		Route::get('trainings', AdminTrainingsPage::class)->name('trainings');
		Route::get('trainings/create', AdminTrainingFormPage::class)->name('trainings.create');
		Route::get('trainings/{training}/edit', AdminTrainingFormPage::class)->name('trainings.edit');
	});
});

app/Livewire/Admin/AdminApplicationFormPage.php
<?php

namespace App\Livewire\Admin;

use App\Livewire\Forms\ApplicationForm;
use App\Models\Application;
use App\Models\Technology;
use Livewire\Attributes\On;
use Livewire\Component;

class AdminApplicationFormPage extends Component
{
    public ApplicationForm $form;
    public $technologies;
 
    public function mount(Application $application)
    {
        $this->form->set($application);
        $this->technologies = Technology::orderBy('name')->get();
    }
 
    public function save()
    {
        $this->form->save();
 
        return $this->redirectRoute('applications.index', navigate: true);
    }
 
    public function removeImage()
    {
        $this->form->image = null;
    }

    public function render()
    {
        return view('livewire.admin.admin-application-form-page');
    }
}

app/Livewire/Admin/AdminApplicationsPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class AdminApplicationsPage extends Component
{
    public function render()
    {
        return view('livewire.admin.admin-applications-page');
    }
}

app/Livewire/Admin/AdminDashboardPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class AdminDashboardPage extends Component
{
    public function render()
    {
        return view('livewire.admin.admin-dashboard-page');
    }
}

app/Livewire/Admin/AdminLoginPage.php
<?php

namespace App\Livewire\Admin;

use App\Models\User;
use App\Notifications\LoginRequestNotification;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;
use Livewire\Component;

class AdminLoginPage extends Component
{
    use Notifiable;

    public $email;

    public function login()
    {
        $email = Str::of($this->email)->trim()->toString();
        $user = User::where('email', $email)->first();

        if (!auth()->user() && $user) {
            $url = URL::temporarySignedRoute(
                'admin.session.create', now()->addMinutes(5), ['email' => $email]
            );

            $user->notify(new LoginRequestNotification($url));
        }

        $this->redirectRoute('home', navigate:true);
    }

    public function render()
    {
        return view('livewire.admin.admin-login-page');
    }
}

app/Livewire/Admin/AdminTechnologiesPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;
use App\Models\Technology;

class AdminTechnologiesPage extends Component
{
    public $technologies;

    public function mount()
    {
        $this->technologies = Technology::orderBy('name')->get();
    }

    public function render()
    {
        return view('livewire.admin.admin-technologies-page');
    }
}

app/Livewire/Admin/AdminTechnologyFormPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;
use App\Models\Technology;
use App\Livewire\Forms\TechnologyForm;

class AdminTechnologyFormPage extends Component
{
    public TechnologyForm $form;
 
    public function mount(Technology $technology)
    {
        $this->form->set($technology);
    }
 
    public function save()
    {
        $this->form->save();
 
        return $this->redirectRoute('admin.technologies', navigate: true);
    }
 
    public function removeImage()
    {
        $this->form->image = null;
    }

    public function render()
    {
        return view('livewire.admin.admin-technology-form-page');
    }
}

app/Livewire/Admin/AdminTrainingFormPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;
use App\Models\Training;
use App\Livewire\Forms\TrainingForm;

class AdminTrainingFormPage extends Component
{
    public TrainingForm $form;
 
    public function mount(Training $training)
    {
        $this->form->set($training);
    }
 
    public function save()
    {
        $this->form->save();
 
        return $this->redirectRoute('trainings.index', navigate: true);
    }
 
    public function removeImage()
    {
        $this->form->image = null;
    }

    public function render()
    {
        return view('livewire.admin.admin-training-form-page');
    }
}

app/Livewire/Admin/AdminTrainingsPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class AdminTrainingsPage extends Component
{
    public function render()
    {
        return view('livewire.admin.admin-trainings-page');
    }
}

app/Livewire/ApplicationsPage.php
<?php

namespace App\Livewire;

use Livewire\Component;
use App\Models\Application;
use Livewire\Attributes\On;
use App\Livewire\ApplicationsPage;

class ApplicationsPage extends Component
{
    public $applications;

    public function mount()
    {
        $this->getApplications();
    }

    #[On('application-deleted')]
    public function getApplications()
    {
        $this->applications = Application::with('media')->get();
    }

    public function delete(Application $application)
    {
        $application?->delete();

        $this->dispatch('application-deleted')->to(ApplicationsPage::class);
    }

    public function render()
    {
        return view('livewire.applications-page');
    }
}

app/Livewire/Components/UploadImageComponent.php
<?php

namespace App\Livewire\Components;

use Livewire\Attributes\Modelable;
use Livewire\Component;
use Livewire\WithFileUploads;

class UploadImageComponent extends Component
{
    use WithFileUploads;

    #[Modelable]
    public $image;

    public $imageUrl;
    public $displayedImage = null;
    public $deleteImage = false;

    public function mount()
    {
        $this->displayedImage = $this->imageUrl ? $this->imageUrl : null;
    }

    public function updatedImage()
    {
        $this->displayedImage = $this->image->temporaryUrl();
        $this->dispatch('image-updated', $this->image);
    }

    public function remove()
    {
        $this->deleteImage = true;
        $this->image = null;
        $this->displayedImage = null;
    }

    public function render()
    {
        return view('livewire.components.upload-image-component');
    }
}

app/Livewire/Forms/ApplicationForm.php
<?php

namespace App\Livewire\Forms;

use App\Models\Application;
use Livewire\Attributes\Validate;
use Livewire\Features\SupportFileUploads\TemporaryUploadedFile;
use Livewire\Form;

class ApplicationForm extends Form
{
    public ?Application $application;
 
    public $id = null;

    #[Validate('required', message: 'Le titre est obligatoire.')]
    public $title = '';
 
    #[Validate('nullable')]
    public $note = '';
 
    #[Validate('required', message: 'La description est obligatoire.')]
    public $description = '';
 
    #[Validate('nullable')]
    public $url = '';
 
    #[Validate('nullable')]
    public $repository = '';
 
    #[Validate('required', message: 'Au moins une technologie est obligatoire.')]
    public $technologies = [];
 
    #[Validate('nullable')]
    #[Validate('image', message: 'Le fichier doit être une image au format jpg, jpeg, png, bmp, gif, svg ou webp.')]
    public $image = null;

    public function set(Application $application)
    {
        $application->load('media');

        $this->application = $application;
 
        $this->id = $application->id;
        $this->title = $application->title;
        $this->note = $application->note;
        $this->description = $application->description;
        $this->url = $application->url;
        $this->repository = $application->repository;
        $this->technologies = $application->technologies ?? [];
        $this->image = null;
    }

    public function save()
    {
        if ($this->id) {
            $this->update();
        } else {
            $this->store();
        }
    }

    public function store()
    {
        if ($this->image !== null) {
            $this->image = TemporaryUploadedFile::unserializeFromLivewireRequest($this->image);
        }

        $this->validate();

        $application = Application::create($this->all());

        if ($this->image !== null) {
            $application->addMedia($this->image)->preservingOriginal()->toMediaCollection('images', 'applications');
        }

        $this->reset();
    }
 
    public function update()
    {
        if ($this->image) {
            $this->image = TemporaryUploadedFile::unserializeFromLivewireRequest($this->image);
        }

        $this->validate();

        $this->application->update($this->all());

        if ($this->image) {
            $this->application->media->first()?->delete();

            $this->application->addMedia($this->image)->preservingOriginal()->toMediaCollection('images', 'applications');
        }

        $this->reset();
    }
}

app/Livewire/Forms/TechnologyForm.php
<?php

namespace App\Livewire\Forms;

use Livewire\Form;
use App\Models\Technology;
use Livewire\Attributes\Validate;

class TechnologyForm extends Form
{
    public ?Technology $technology;
 
    public $id = null;

    #[Validate('required', message: 'Le nom est obligatoire.')]
    public $name = '';

    public function set(Technology $technology)
    {
        $this->technology = $technology;
 
        $this->id = $technology->id;
        $this->name = $technology->name;
    }

    public function save()
    {
        if ($this->id) {
            $this->update();
        } else {
            $this->store();
        }
    }

    public function store()
    {
        $this->validate();

        $technology = Technology::create($this->all());

        $this->reset();
    }
 
    public function update()
    {
        $this->validate();

        $this->technology->update($this->all());

        $this->reset();
    }
}

app/Livewire/Forms/TrainingForm.php
<?php

namespace App\Livewire\Forms;

use Livewire\Form;
use App\Models\Training;
use Livewire\Attributes\Validate;
use Livewire\Features\SupportFileUploads\TemporaryUploadedFile;

class TrainingForm extends Form
{
    public ?Training $training;
 
    public $id = null;

    #[Validate('required', message: 'Le titre est obligatoire.')]
    public $title = '';
 
    #[Validate('required', message: 'Le sous-titre est obligatoire.')]
    public $subtitle = '';
 
    #[Validate('nullable')]
    public $hook = '';
 
    #[Validate('nullable')]
    #[Validate('image', message: 'Le fichier doit être une image au format jpg, jpeg, png, bmp, gif, svg ou webp.')]
    public $image = null;

    public function set(Training $training)
    {
        $training->load('media');

        $this->training = $training;
 
        $this->id = $training->id;
        $this->title = $training->title;
        $this->subtitle = $training->subtitle;
        $this->hook = $training->hook;
        $this->image = null;
    }

    public function save()
    {
        if ($this->id) {
            $this->update();
        } else {
            $this->store();
        }
    }

    public function store()
    {
        if ($this->image) {
            $this->image = TemporaryUploadedFile::unserializeFromLivewireRequest($this->image);
        }

        $this->validate();

        $training = Training::create($this->all());

        $training->addMedia($this->image)->preservingOriginal()->toMediaCollection('images', 'trainings');

        $this->reset();
    }
 
    public function update()
    {
        if ($this->image) {
            $this->image = TemporaryUploadedFile::unserializeFromLivewireRequest($this->image);
        }

        $this->validate();

        $this->training->update($this->all());

        if ($this->image) {
            $this->training->media->first()->delete();

            $this->training->addMedia($this->image)->preservingOriginal()->toMediaCollection('images', 'trainings');
        }

        $this->reset();
    }
}

app/Livewire/HomePage.php
<?php

namespace App\Livewire;

use Livewire\Component;

class HomePage extends Component
{
    public function render()
    {
        return view('livewire.home-page');
    }
}

app/Livewire/TrainingsPage.php
<?php

namespace App\Livewire;

use Livewire\Component;
use App\Models\Training;

class TrainingsPage extends Component
{
    public $trainings;

    public function mount()
    {
        $this->trainings = Training::with('media')->get();
    }

    public function render()
    {
        return view('livewire.trainings-page');
    }
}

resources/views/livewire/admin/admin-application-form-page.blade.php
<section class="flex flex-col justify-center items-center gap-4 px-8 py-8">
    <form class="w-full lg:w-2/3 flex flex-grow gap-8 justify-center items-center" wire:submit="save()">
        <livewire:components.upload-image-component wire:model="form.image" imageUrl="{{ $form->application->first_media_url }}"></livewire:components.upload-image-component>

        <div class="space-y-4">
            <div class="w-full flex flex-col gap-1">
                <x-label>Titre</x-label>
                <input wire:model.live="form.title" class="outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="Titre" type="text" />
                @error('form.title')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <div class="w-full flex flex-col gap-1">
                <x-label>Note</x-label>
                <input wire:model.live="form.note" class="outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="Note" type="text" />
                @error('form.note')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <div class="w-full flex flex-col gap-1">
                <x-label>Description</x-label>
                <textarea wire:model.live="form.description" class="outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="Description"></textarea>
                @error('form.description')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <div class="w-full flex flex-col gap-1">
                <x-label>URL</x-label>
                <input wire:model.live="form.url" class="outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="URL" type="text" />
                @error('form.url')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <div class="w-full flex flex-col gap-1">
                <x-label>Dépôt</x-label>
                <input wire:model.live="form.repository" class="outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="Dépôt" type="text" />
                @error('form.repository')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <div class="w-full flex flex-col gap-1">
                <x-label>Technologies</x-label>
                <div class="flex items-center gap-2 flex-wrap">
                    @foreach ($technologies as $technology)
                        <input type="checkbox" id="{{ 'technology-'.$technology->id }}" value="{{ $technology->name }}" wire:model.live="form.technologies" @checked(in_array($technology->name, $form->technologies)) class="hidden" />

                        <label @class([
                            'cursor-pointer transition-all rounded-lg border border-yellow rounded-lg text-sm px-4 py-2',
                            'bg-yellow' => in_array($technology->name, $form->technologies)
                        ]) for="{{ 'technology-'.$technology->id }}">{{ $technology->name }}</label>
                    @endforeach
                </div>
                @error('form.technologies')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <button class="w-full px-4 py-2 border border-yellow hover:bg-yellow rounded-lg transition-all" type="submit">Enregistrer</button>
        </div>
    </form>
</section>

resources/views/livewire/admin/admin-applications-page.blade.php
<div>
    {{-- Stop trying to control. --}}
</div>

resources/views/livewire/admin/admin-dashboard-page.blade.php
<div class="py-8 px-8 lg:px-20">
    {{-- <a href="{{ route('admin.trainings') }}">Formations</a> --}}
    <a href="{{ route('admin.applications') }}" wire:navigate>Applications</a>

    <a href="{{ route('admin.technologies') }}" wire:navigate>Technologies</a>
</div>

resources/views/livewire/admin/admin-login-page.blade.php
<section class="min-h-[calc(100vh-8rem)] flex flex-col justify-center items-center gap-4 px-8">
    <form class="w-full lg:w-80 flex flex-grow flex-col gap-4 justify-center items-center" wire:submit="login()">
        <span class="text-yellow"><i class="fas fa-lock fa-3x"></i></span>

        <input wire:model="email" class="w-full outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="Adresse mail" type="text" />

        <button class="w-full px-4 py-2 border border-yellow hover:bg-yellow rounded-lg transition-all" type="submit">Se connecter</button>
    </form>
</section>

resources/views/livewire/admin/admin-technologies-page.blade.php
<section class="px-8 py-8 lg:px-20 space-y-8">
    <div class="flex items-center">
        <h1 class="text-3xl text-gray-dark">TECHNOLOGIES</h1>

        @auth
            <a class="ml-4 text-3xl text-gray-light hover:text-yellow transition-all" href="{{ route('admin.technologies.create') }}" wire:navigate><i class="fas fa-plus"></i></a>
        @endauth
    </div>

    <div class="flex items-center gap-4">
        @foreach ($technologies as $technology)
            <a href="{{ route('admin.technologies.edit', compact('technology')) }}" class="border border-gray-medium hover:bg-gray-medium hover:text-white px-4 py-2 rounded-full" wire:navigate>{{ $technology->name }}</a>
        @endforeach
    </div>
</section>

resources/views/livewire/admin/admin-technology-form-page.blade.php
<section class="flex flex-col justify-center items-center gap-4 px-8 py-8">
    <form class="w-full lg:w-2/3 flex flex-grow gap-8 justify-center items-center" wire:submit="save()">
        <div class="space-y-4">
            <div class="w-full flex flex-col gap-1">
                <x-label>Nom</x-label>
                <input wire:model.live="form.name" class="outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="Titre" type="text" />
                @error('form.name')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <button class="w-full px-4 py-2 border border-yellow hover:bg-yellow rounded-lg transition-all" type="submit">Enregistrer</button>
        </div>
    </form>
</section>

resources/views/livewire/admin/admin-training-form-page.blade.php
<section class="flex flex-col justify-center items-center gap-4 px-8 py-8">
    <form class="w-full lg:w-2/3 flex flex-grow gap-8 justify-center items-center" wire:submit="save()">
        <livewire:components.upload-image-component wire:model="form.image" imageUrl="{{ $form->training->first_media_url }}"></livewire:components.upload-image-component>

        <div class="space-y-4">
            <div class="w-full flex flex-col gap-1">
                <x-label>Titre</x-label>
                <input wire:model.live="form.title" class="outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="Titre" type="text" />
                @error('form.title')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <div class="w-full flex flex-col gap-1">
                <x-label>Sous-titre</x-label>
                <input wire:model.live="form.subtitle" class="outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="Sous-titre" type="text" />
                @error('form.subtitle')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <div class="w-full flex flex-col gap-1">
                <x-label>Accroche</x-label>
                <textarea wire:model.live="form.hook" class="outline-none px-4 py-2 border border-gray-light focus:border-yellow rounded-lg" placeholder="hook"></textarea>
                @error('form.hook')
                    <span class="text-sm text-red-500">{{ $message }}</span>
                @enderror 
            </div>

            <button class="w-full px-4 py-2 border border-yellow hover:bg-yellow rounded-lg transition-all" type="submit">Enregistrer</button>
        </div>
    </form>
</section>

resources/views/livewire/admin/admin-trainings-page.blade.php
<div>
    {{-- A good traveler has no fixed plans and is not intent upon arriving. --}}
</div>