routes/web.php
<?php

use App\Livewire\HomePage;
use App\Livewire\ContactPage;
use App\Livewire\TrainingsPage;
use App\Livewire\ApplicationsPage;
use Illuminate\Support\Facades\Route;
use App\Livewire\Admin\AdminLoginPage;
use App\Livewire\Admin\AdminDashboardPage;
use App\Livewire\Admin\AdminTrainingsPage;
use App\Http\Controllers\SessionController;
use App\Livewire\Admin\AdminApplicationsPage;
use App\Livewire\Admin\AdminTechnologiesPage;
use App\Livewire\Admin\AdminTrainingFormPage;
use App\Livewire\Admin\AdminTechnologyFormPage;
use App\Livewire\Admin\AdminApplicationFormPage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', HomePage::class)->name('home');

Route::get('applications', ApplicationsPage::class)->name('applications.index');

Route::get('trainings', TrainingsPage::class)->name('trainings.index');

Route::prefix('admin')->name('admin.')->group(function () {
	Route::get('login', AdminLoginPage::class)->name('login');
	Route::get('session/create', [SessionController::class, 'create'])->name('session.create');

	Route::middleware('auth')->group(function () {
		Route::get('dashboard', AdminDashboardPage::class)->name('dashboard');
		Route::get('session/destroy', [SessionController::class, 'destroy'])->name('session.destroy');

		Route::get('applications', AdminApplicationsPage::class)->name('applications');
		Route::get('applications/create', AdminApplicationFormPage::class)->name('applications.create');
		Route::get('applications/{application}/edit', AdminApplicationFormPage::class)->name('applications.edit');

		Route::get('technologies', AdminTechnologiesPage::class)->name('technologies');
		Route::get('technologies/create', AdminTechnologyFormPage::class)->name('technologies.create');
		Route::get('technologies/{technology}/edit', AdminTechnologyFormPage::class)->name('technologies.edit');

		Route::get('trainings', AdminTrainingsPage::class)->name('trainings');
		Route::get('trainings/create', AdminTrainingFormPage::class)->name('trainings.create');
		Route::get('trainings/{training}/edit', AdminTrainingFormPage::class)->name('trainings.edit');
	});
});

resources/views/partials/_bottom.blade.php
<div class="flex justify-between items-center bg-gray-dark text-white px-8 lg:px-20 py-6">
    <span>Copyright © Prestidigitaweb 2020-{{ date('Y') }} - Tous droits de reproduction interdits</span>

    <a class="text-yellow" href="docs/cgu.pdf" target="_blank">CGU</a>
</div>

resources/views/partials/_footer.blade.php
<footer class="flex flex-col lg:flex-row lg:justify-between lg:items-center bg-gray-medium text-white px-8 lg:px-20 py-6 gap-8 lg:gap-0" id="contact">
    <div class="space-y-2">
        <p class="text-2xl font-bold mb-4">Propriétaire du site</p>
        <p>Erhart Vincent</p>
        <p>15000 Aurillac</p>
        <p><span class="text-yellow mr-2"><i class="fas fa-phone"></i></span>06 25 19 68 75</p>
        <p><a class="text-yellow" href="mailto:vincenterhart.formateur@gmail.com"><span class="text-yellow mr-2"><i class="fas fa-at"></i></span>vincenterhart.formateur@gmail.com</a></p>
    </div>

    <div class="space-y-2">
        <p class="text-2xl font-bold mb-4">Micro-entreprise</p>
        <p>EI Erhart Vincent</p>
        <p>SIRET : 510 350 150 00023 / APE : 8559A</p>
        <p>Déclaration d’activité numéro 84150323615 auprès du préfet de région Auvergne-Rhône-Alpes</p>
        <p>Assurance Hiscox : HSXPM310024158</p>
    </div>

    <div class="space-y-2">
        <p class="text-2xl font-bold mb-4">Hébergement du site</p>
        <p>IONOS</p>
        <p>7, place de la Gare</p>
        <p>57200 Sarreguemines</p>
        <p>Téléphone : 09 70 80 89 11</p>
    </div>
</footer>

resources/views/partials/_header.blade.php
<header class="z-20 sticky top-0 h-20 lg:h-32 flex justify-between items-center bg-gray-dark text-white px-8 lg:px-20">
    <a
        class="font-signature text-yellow text-3xl lg:text-6xl"
        @if (Route::is('home'))
            href="#home"
        @else
            href="{{ route('home') }}"
            wire:navigate.hover
        @endif
    >
        P<span class="hidden lg:inline">resti</span> D<span class="hidden lg:inline">igita</span> W<span class="hidden lg:inline">eb</span>
    </a>

    <div
        x-data="{
            mobile: false,
            show: false,
            width: 0,
            getWidth() {
                return window.innerWidth > 0 ? window.innerWidth : screen.width;
            }
        }"
        x-on:resize.window="width = getWidth()"
        x-effect="mobile = width > 1024 ? false : true"
        x-effect="show = width > 1024 ? false : true"
        x-init="
            width = getWidth();
        "
        x-on:click="show = true"
        class="flex justify-center items-center"
    >
        <i class="fas fa-bars fa-2x" x-cloak x-show="mobile" x-on:click="show = !show" x-transition></i>

	    <nav class="flex flex-col border border-gray-light lg:border-0 absolute top-0 right-0 lg:relative px-8 py-6 lg:p-0 lg:flex-row lg:items-center gap-8 text-xl bg-gray-dark" x-cloak x-show="!mobile || show" x-transition x-on:click.outside="show = false">
	        <a
	            @class(['transition-all hover:text-yellow', 'text-yellow' => Route::is('home')])
	            @if (Route::is('home'))
	                href="#home"
	            @else
	                href="{{ route('home') }}"
	                wire:navigate.hover
	            @endif
	        >
	            Accueil
	        </a>

	        <a @class(['transition-all hover:text-yellow', 'text-yellow' => Route::is('trainings.*')]) href="{{ route('trainings.index') }}" wire:navigate.hover>Formations</a>

	        <a @class(['transition-all hover:text-yellow', 'text-yellow' => Route::is('applications.*')]) href="{{ route('applications.index') }}" wire:navigate.hover>Développement web</a>

	        @auth
	            <a @class(['transition-all hover:text-yellow', 'text-yellow' => Route::is('admin.dashboard')]) href="{{ route('admin.dashboard') }}" wire:navigate.hover>Tableau de bord</a>

	            <a class="transition-all hover:text-yellow" href="{{ route('admin.session.destroy') }}" wire:navigate.hover>Se déconnecter</a>
	        @endauth
	    </nav>
    </div>
</header>