routes/web.php
<?php

use App\Livewire\HomePage;
use App\Livewire\ContactPage;
use App\Livewire\TrainingsPage;
use App\Livewire\ApplicationsPage;
use Illuminate\Support\Facades\Route;
use App\Livewire\Admin\AdminLoginPage;
use App\Livewire\Admin\AdminDashboardPage;
use App\Livewire\Admin\AdminTrainingsPage;
use App\Http\Controllers\SessionController;
use App\Livewire\Admin\AdminApplicationsPage;
use App\Livewire\Admin\AdminTechnologiesPage;
use App\Livewire\Admin\AdminTrainingFormPage;
use App\Livewire\Admin\AdminTechnologyFormPage;
use App\Livewire\Admin\AdminApplicationFormPage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', HomePage::class)->name('home');

Route::get('applications', ApplicationsPage::class)->name('applications.index');

Route::get('trainings', TrainingsPage::class)->name('trainings.index');

Route::prefix('admin')->name('admin.')->group(function () {
	Route::get('login', AdminLoginPage::class)->name('login');
	Route::get('session/create', [SessionController::class, 'create'])->name('session.create');

	Route::middleware('auth')->group(function () {
		Route::get('dashboard', AdminDashboardPage::class)->name('dashboard');
		Route::get('session/destroy', [SessionController::class, 'destroy'])->name('session.destroy');

		Route::get('applications', AdminApplicationsPage::class)->name('applications');
		Route::get('applications/create', AdminApplicationFormPage::class)->name('applications.create');
		Route::get('applications/{application}/edit', AdminApplicationFormPage::class)->name('applications.edit');

		Route::get('technologies', AdminTechnologiesPage::class)->name('technologies');
		Route::get('technologies/create', AdminTechnologyFormPage::class)->name('technologies.create');
		Route::get('technologies/{technology}/edit', AdminTechnologyFormPage::class)->name('technologies.edit');

		Route::get('trainings', AdminTrainingsPage::class)->name('trainings');
		Route::get('trainings/create', AdminTrainingFormPage::class)->name('trainings.create');
		Route::get('trainings/{training}/edit', AdminTrainingFormPage::class)->name('trainings.edit');
	});
});

app/Livewire/Admin/AdminApplicationFormPage.php
<?php

namespace App\Livewire\Admin;

use App\Livewire\Forms\ApplicationForm;
use App\Models\Application;
use App\Models\Technology;
use Livewire\Attributes\On;
use Livewire\Component;

class AdminApplicationFormPage extends Component
{
    public ApplicationForm $form;
    public $technologies;
 
    public function mount(Application $application)
    {
        $this->form->set($application);
        $this->technologies = Technology::orderBy('name')->get();
    }
 
    public function save()
    {
        $this->form->save();
 
        return $this->redirectRoute('applications.index', navigate: true);
    }
 
    public function removeImage()
    {
        $this->form->image = null;
    }

    public function render()
    {
        return view('livewire.admin.admin-application-form-page');
    }
}

app/Livewire/Admin/AdminApplicationsPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class AdminApplicationsPage extends Component
{
    public function render()
    {
        return view('livewire.admin.admin-applications-page');
    }
}

app/Livewire/Admin/AdminDashboardPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class AdminDashboardPage extends Component
{
    public function render()
    {
        return view('livewire.admin.admin-dashboard-page');
    }
}

app/Livewire/Admin/AdminLoginPage.php
<?php

namespace App\Livewire\Admin;

use App\Models\User;
use App\Notifications\LoginRequestNotification;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;
use Livewire\Component;

class AdminLoginPage extends Component
{
    use Notifiable;

    public $email;

    public function login()
    {
        $email = Str::of($this->email)->trim()->toString();
        $user = User::where('email', $email)->first();

        if (!auth()->user() && $user) {
            $url = URL::temporarySignedRoute(
                'admin.session.create', now()->addMinutes(5), ['email' => $email]
            );

            $user->notify(new LoginRequestNotification($url));
        }

        $this->redirectRoute('home', navigate:true);
    }

    public function render()
    {
        return view('livewire.admin.admin-login-page');
    }
}

app/Livewire/Admin/AdminTechnologiesPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;
use App\Models\Technology;

class AdminTechnologiesPage extends Component
{
    public $technologies;

    public function mount()
    {
        $this->technologies = Technology::orderBy('name')->get();
    }

    public function render()
    {
        return view('livewire.admin.admin-technologies-page');
    }
}

app/Livewire/Admin/AdminTechnologyFormPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;
use App\Models\Technology;
use App\Livewire\Forms\TechnologyForm;

class AdminTechnologyFormPage extends Component
{
    public TechnologyForm $form;
 
    public function mount(Technology $technology)
    {
        $this->form->set($technology);
    }
 
    public function save()
    {
        $this->form->save();
 
        return $this->redirectRoute('admin.technologies', navigate: true);
    }
 
    public function removeImage()
    {
        $this->form->image = null;
    }

    public function render()
    {
        return view('livewire.admin.admin-technology-form-page');
    }
}

app/Livewire/Admin/AdminTrainingFormPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;
use App\Models\Training;
use App\Livewire\Forms\TrainingForm;

class AdminTrainingFormPage extends Component
{
    public TrainingForm $form;
 
    public function mount(Training $training)
    {
        $this->form->set($training);
    }
 
    public function save()
    {
        $this->form->save();
 
        return $this->redirectRoute('trainings.index', navigate: true);
    }
 
    public function removeImage()
    {
        $this->form->image = null;
    }

    public function render()
    {
        return view('livewire.admin.admin-training-form-page');
    }
}

app/Livewire/Admin/AdminTrainingsPage.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class AdminTrainingsPage extends Component
{
    public function render()
    {
        return view('livewire.admin.admin-trainings-page');
    }
}

app/Livewire/ApplicationsPage.php
<?php

namespace App\Livewire;

use Livewire\Component;
use App\Models\Application;
use Livewire\Attributes\On;
use App\Livewire\ApplicationsPage;

class ApplicationsPage extends Component
{
    public $applications;

    public function mount()
    {
        $this->getApplications();
    }

    #[On('application-deleted')]
    public function getApplications()
    {
        $this->applications = Application::with('media')->get();
    }

    public function delete(Application $application)
    {
        $application?->delete();

        $this->dispatch('application-deleted')->to(ApplicationsPage::class);
    }

    public function render()
    {
        return view('livewire.applications-page');
    }
}

app/Livewire/Components/UploadImageComponent.php
<?php

namespace App\Livewire\Components;

use Livewire\Attributes\Modelable;
use Livewire\Component;
use Livewire\WithFileUploads;

class UploadImageComponent extends Component
{
    use WithFileUploads;

    #[Modelable]
    public $image;

    public $imageUrl;
    public $displayedImage = null;
    public $deleteImage = false;

    public function mount()
    {
        $this->displayedImage = $this->imageUrl ? $this->imageUrl : null;
    }

    public function updatedImage()
    {
        $this->displayedImage = $this->image->temporaryUrl();
        $this->dispatch('image-updated', $this->image);
    }

    public function remove()
    {
        $this->deleteImage = true;
        $this->image = null;
        $this->displayedImage = null;
    }

    public function render()
    {
        return view('livewire.components.upload-image-component');
    }
}

app/Livewire/Forms/ApplicationForm.php
<?php

namespace App\Livewire\Forms;

use App\Models\Application;
use Livewire\Attributes\Validate;
use Livewire\Features\SupportFileUploads\TemporaryUploadedFile;
use Livewire\Form;

class ApplicationForm extends Form
{
    public ?Application $application;
 
    public $id = null;

    #[Validate('required', message: 'Le titre est obligatoire.')]
    public $title = '';
 
    #[Validate('nullable')]
    public $note = '';
 
    #[Validate('required', message: 'La description est obligatoire.')]
    public $description = '';
 
    #[Validate('nullable')]
    public $url = '';
 
    #[Validate('nullable')]
    public $repository = '';
 
    #[Validate('required', message: 'Au moins une technologie est obligatoire.')]
    public $technologies = [];
 
    #[Validate('nullable')]
    #[Validate('image', message: 'Le fichier doit être une image au format jpg, jpeg, png, bmp, gif, svg ou webp.')]
    public $image = null;

    public function set(Application $application)
    {
        $application->load('media');

        $this->application = $application;
 
        $this->id = $application->id;
        $this->title = $application->title;
        $this->note = $application->note;
        $this->description = $application->description;
        $this->url = $application->url;
        $this->repository = $application->repository;
        $this->technologies = $application->technologies ?? [];
        $this->image = null;
    }

    public function save()
    {
        if ($this->id) {
            $this->update();
        } else {
            $this->store();
        }
    }

    public function store()
    {
        if ($this->image !== null) {
            $this->image = TemporaryUploadedFile::unserializeFromLivewireRequest($this->image);
        }

        $this->validate();

        $application = Application::create($this->all());

        if ($this->image !== null) {
            $application->addMedia($this->image)->preservingOriginal()->toMediaCollection('images', 'applications');
        }

        $this->reset();
    }
 
    public function update()
    {
        if ($this->image) {
            $this->image = TemporaryUploadedFile::unserializeFromLivewireRequest($this->image);
        }

        $this->validate();

        $this->application->update($this->all());

        if ($this->image) {
            $this->application->media->first()?->delete();

            $this->application->addMedia($this->image)->preservingOriginal()->toMediaCollection('images', 'applications');
        }

        $this->reset();
    }
}

app/Livewire/Forms/TechnologyForm.php
<?php

namespace App\Livewire\Forms;

use Livewire\Form;
use App\Models\Technology;
use Livewire\Attributes\Validate;

class TechnologyForm extends Form
{
    public ?Technology $technology;
 
    public $id = null;

    #[Validate('required', message: 'Le nom est obligatoire.')]
    public $name = '';

    public function set(Technology $technology)
    {
        $this->technology = $technology;
 
        $this->id = $technology->id;
        $this->name = $technology->name;
    }

    public function save()
    {
        if ($this->id) {
            $this->update();
        } else {
            $this->store();
        }
    }

    public function store()
    {
        $this->validate();

        $technology = Technology::create($this->all());

        $this->reset();
    }
 
    public function update()
    {
        $this->validate();

        $this->technology->update($this->all());

        $this->reset();
    }
}

app/Livewire/Forms/TrainingForm.php
<?php

namespace App\Livewire\Forms;

use Livewire\Form;
use App\Models\Training;
use Livewire\Attributes\Validate;
use Livewire\Features\SupportFileUploads\TemporaryUploadedFile;

class TrainingForm extends Form
{
    public ?Training $training;
 
    public $id = null;

    #[Validate('required', message: 'Le titre est obligatoire.')]
    public $title = '';
 
    #[Validate('required', message: 'Le sous-titre est obligatoire.')]
    public $subtitle = '';
 
    #[Validate('nullable')]
    public $hook = '';
 
    #[Validate('nullable')]
    #[Validate('image', message: 'Le fichier doit être une image au format jpg, jpeg, png, bmp, gif, svg ou webp.')]
    public $image = null;

    public function set(Training $training)
    {
        $training->load('media');

        $this->training = $training;
 
        $this->id = $training->id;
        $this->title = $training->title;
        $this->subtitle = $training->subtitle;
        $this->hook = $training->hook;
        $this->image = null;
    }

    public function save()
    {
        if ($this->id) {
            $this->update();
        } else {
            $this->store();
        }
    }

    public function store()
    {
        if ($this->image) {
            $this->image = TemporaryUploadedFile::unserializeFromLivewireRequest($this->image);
        }

        $this->validate();

        $training = Training::create($this->all());

        $training->addMedia($this->image)->preservingOriginal()->toMediaCollection('images', 'trainings');

        $this->reset();
    }
 
    public function update()
    {
        if ($this->image) {
            $this->image = TemporaryUploadedFile::unserializeFromLivewireRequest($this->image);
        }

        $this->validate();

        $this->training->update($this->all());

        if ($this->image) {
            $this->training->media->first()->delete();

            $this->training->addMedia($this->image)->preservingOriginal()->toMediaCollection('images', 'trainings');
        }

        $this->reset();
    }
}

app/Livewire/HomePage.php
<?php

namespace App\Livewire;

use Livewire\Component;

class HomePage extends Component
{
    public function render()
    {
        return view('livewire.home-page');
    }
}

app/Livewire/TrainingsPage.php
<?php

namespace App\Livewire;

use Livewire\Component;
use App\Models\Training;

class TrainingsPage extends Component
{
    public $trainings;

    public function mount()
    {
        $this->trainings = Training::with('media')->get();
    }

    public function render()
    {
        return view('livewire.trainings-page');
    }
}

resources/views/livewire/applications-page.blade.php
<div class="py-8 px-8 lg:px-20">
    <div class="flex items-center">
        <h1 class="text-3xl text-gray-dark">EXEMPLES D'APPLICATIONS DEVELOPPEES</h1>

        @auth
            <a class="ml-4 text-3xl text-gray-light hover:text-yellow transition-all" href="{{ route('admin.applications.create') }}" wire:navigate><i class="fas fa-plus"></i></a>
        @endauth
    </div>

    <div class="py-8 grid grid-cols-1 lg:grid-cols-2 gap-8">
        @foreach ($applications as $application)
            <x-application-card :application="$application"></x-application-card>
        @endforeach
    </div>
</div>

resources/views/livewire/home-page.blade.php
<div>
    <section class="min-h-[calc(100vh-8rem)] flex flex-col lg:flex-row justify-start px-8 lg:px-20 lg:justify-center items-center gap-8 lg:gap-20 text-center bg-home bg-no-repeat bg-cover text-white py-8">
        <div class="flex flex-col justify-center items-center gap-8">
            <img class="border-8 border-yellow rounded-full" src="{{ asset('images/vincenterhart.jpg') }}" alt="Vincent Erhart" />

            <div class="flex flex-col items-center gap-4">
                <span class="text-3xl text-white font-bold">Vincent Erhart</span>

                <span class="text-xl italic text-white">Formateur et développeur fullstack</span>

                <p class="text-base">06 25 19 68 75</p>
                <p class="text-base"><a class="text-yellow" href="mailto:vincenterhart.formateur@gmail.com">vincenterhart.formateur@gmail.com</a></p>
                <p class="text-3xl">
                    <a href="https://www.linkedin.com/in/vincent-erhart-89829115a" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
                </p>
            </div>

            <a class="lg:hidden max-w-fit px-8 py-4 rounded-lg bg-yellow text-xl font-bold text-gray-dark" href="#services">PRESTATIONS</a>

            <a class="lg:hidden max-w-fit px-8 py-4 rounded-lg bg-yellow text-xl font-bold text-gray-dark" href="#testimonials">TEMOIGNAGES</a>
        </div>

        <div class="hidden lg:flex flex-col justify-center items-center gap-20 lg:gap-8">
            <span class="text-3xl italic">Découvrez la magie du web</span>

            <h1 class="text-6xl font-bold">PRESTI DIGITA WEB</h1>

            <span class="text-3xl italic">La magie, ça se prépare</span>

            <div class="flex flex-col lg:flex-row items-center gap-8">
                <a class="max-w-fit px-8 py-4 rounded-lg bg-yellow text-xl font-bold text-gray-dark" href="#services">PRESTATIONS</a>

                <a class="max-w-fit px-8 py-4 rounded-lg bg-yellow text-xl font-bold text-gray-dark" href="#testimonials">TEMOIGNAGES</a>
            </div>
        </div>
    </section>

    <section class="min-h-[calc(100vh-8rem)] flex flex-col justify-center items-center gap-8 text-center text-gray-dark px-8 lg:px-20 py-8 bg-gray-medium text-white" id="services">
        <h2 class="text-5xl font-bold">PRESTATIONS</h2>

        <span class="text-xl italic">Des formations et des applications web sur mesure</span>

        <div class="flex flex-col lg:flex-row justify-around gap-8 lg:gap-0">
            <x-service-card
                route="{{ route('trainings.index') }}"
                icon="fas fa-graduation-cap"
                title="Formations"
                description="Motivez vos apprenants avec des formations dynamiques et ludiques"
            ></x-service-card>

            <x-service-card
                route="{{ route('applications.index') }}"
                icon="fas fa-laptop-code"
                title="Développement web"
                description="Simplifiez la gestion de vos données professionnelles avec une application web sur mesure"
            ></x-service-card>
        </div>
    </section>

    <section class="min-h-[calc(100vh-8rem)] flex flex-col justify-center items-center gap-8 text-center text-gray-dark px-8 lg:px-20 py-8" id="testimonials">
        <h2 class="text-3xl text-gray-dark font-bold">ILS ME FONT CONFIANCE</h2>

        <article class="flex justify-around items-center flex-wrap gap-8">
            <div class="p-4 border border-gray-light shadow-lg rounded-lg bg-gray-medium">
                <img class="h-16" src="{{ asset('images/clients/doing.jpg') }}" />
            </div>

            <div class="p-4 border border-gray-light shadow-lg rounded-lg bg-white">
                <img class="h-16" src="{{ asset('images/clients/fdseo.jpg') }}" />
            </div>

            <div class="p-4 border border-gray-light shadow-lg rounded-lg bg-white">
                <img class="h-16" src="{{ asset('images/clients/lbpf.jpg') }}" />
            </div>

            <div class="p-4 border border-gray-light shadow-lg rounded-lg bg-white">
                <img class="h-16" src="{{ asset('images/clients/lyceesaintgeraud.jpg') }}" />
            </div>

            <div class="p-4 border border-gray-light shadow-lg rounded-lg bg-black">
                <img class="h-16" src="{{ asset('images/clients/nydvelos.jpg') }}" />
            </div>
        </article>

        <article class="w-full lg:w-1/2 flex flex-col text-justify gap-4">
            <div class="space-y-2">
                <span class="text-lg font-bold text-gray-dark">Jean-Sébastien Pin - Nyd-Vélos</span>

                <div class="text-gray-light space-y-1">
                    <p>
                        Excellente collaboration avec Vincent qui s'est chargé de développer des Features Back office, en PHP Laravel sur de l'existant. J'ai apprécié la capacité de Vincent à s'impliquer pleinement dans le projet. La volonté de comprendre des process métiers spécifiques. Les efforts et la recherche face aux imprévus.
                    </p>

                    <p>
                        Bref vous pouvez travailler avec Vincent en toute confiance. Dès lors qu'il est engagé dans un projet il va au bout.
                    </p>
                </div>
            </div>

            <div class="space-y-2">
                <span class="text-lg font-bold text-gray-dark">Frédéric Devaux - FDSEO</span>

                <div class="text-gray-light space-y-1">
                    <p>
                        Je recommande très fortement Vincent, non seulement pour ses qualités techniques, mais aussi pour ses qualités humaines.
                    </p>

                    <p>
                        Vincent est une personne très à l'écoute, il est bien organisé et gère très bien ses projets.
                    </p>
                    
                    <p>
                        Dans le cadre de mon projet, il a su rapidement s'adapter au code source existant pour développer les fonctionnalités demandées, un vrai sans faute !
                    </p>
                </div>
            </div>

            <div class="space-y-2">
                <span class="text-lg font-bold text-gray-dark">Karine Gaumat - Le Bon Plan Formation</span>

                <div class="text-gray-light space-y-1">
                    <p>
                        Vincent a su fait preuve d'écoute et de réactivité tout au long de notre collaboration. Il a réussi à comprendre mes besoins rapidement. Grâce à cela, j'ai à ce jour une application très fonctionnelle et très intuitive qui me permet de gagner beaucoup de temps.
                    </p>
                </div>
            </div>
        </article>
    </section>
</div>

resources/views/livewire/trainings-page.blade.php
<div class="py-8 px-8 lg:px-20">
    <div class="flex items-center">
        <h1 class="text-3xl text-gray-dark">EXEMPLES DE FORMATION DISPENSEES</h1>

        @auth
            <a class="ml-4 text-3xl text-gray-light hover:text-yellow transition-all" href="{{ route('admin.trainings.create') }}" wire:navigate><i class="fas fa-plus"></i></a>
        @endauth
    </div>

    <div class="py-8 grid grid-cols-1 lg:grid-cols-2 gap-8">
        @foreach ($trainings as $training)
            <x-training-card :training="$training"></x-training-card>
        @endforeach
    </div>
</div>